import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage();
await page.setViewportSize({width:375,height:800});
await page.goto('http://localhost:3000/login', {waitUntil:'networkidle'});
await page.waitForTimeout(1000);
await page.locator('input[type="email"]').first().fill('gabriel@google.com');
await page.locator('input[type="password"]').first().fill('1q2w3e4r5t');
await page.locator('button:has-text("Iniciar sesión")').click();
await page.waitForTimeout(2500);
await page.goto('http://localhost:3000/kids/1b98f3d3-2905-465d-afc8-92fa74b4c53c', {waitUntil:'domcontentloaded', timeout:15000}).catch(e=>console.log('nav err',e.message));
await page.waitForTimeout(2500);
await page.screenshot({path:'.playwright-mcp/12-perfil-activa-375.png', fullPage:true});
console.log('done 375 activa');

await page.setViewportSize({width:1280,height:800});
await page.goto('http://localhost:3000/activar-cuenta?code=K9X2P&email=maria.test.e2e@example.com', {waitUntil:'networkidle'});
await page.waitForTimeout(2500);
await page.locator('input[type="password"]').first().fill('123');
await page.locator('button:has-text("Activar mi cuenta")').click();
await page.waitForTimeout(1000);
await page.screenshot({path:'.playwright-mcp/12-activar-cuenta-password-error-1280.png', fullPage:true});
console.log('done pwd error 1280');
await page.screenshot({path:'.playwright-mcp/12-activar-cuenta-password-error-375.png', fullPage:true});
await page.setViewportSize({width:375,height:800});
await page.waitForTimeout(500);
await page.screenshot({path:'.playwright-mcp/12-activar-cuenta-password-error-375.png', fullPage:true});
console.log('done pwd error 375');

await page.setViewportSize({width:1280,height:800});
await page.goto('http://localhost:3000/activar-cuenta?code=ZZZZZ&email=invalid@x.com', {waitUntil:'networkidle'});
await page.waitForTimeout(2500);
await page.screenshot({path:'.playwright-mcp/12-activar-cuenta-invalid-1280.png', fullPage:true});
console.log('done invalid 1280');
await page.setViewportSize({width:375,height:800});
await page.waitForTimeout(500);
await page.screenshot({path:'.playwright-mcp/12-activar-cuenta-invalid-375.png', fullPage:true});
console.log('done invalid 375');
await browser.close();
